apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/gitops-config
    targetRevision: HEAD
    path: base/web-app
    kustomize:
      namePrefix: prod-
      commonLabels:
        environment: prod
      replicas:
      - name: web-app
        count: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
