apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-operator
  template:
    metadata:
      labels:
        app: webapp-operator
    spec:
      serviceAccountName: webapp-operator
      containers:
      - name: operator
        image: webapp-operator:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: METRICS_PORT
          value: "8000"
        ports:
        - containerPort: 8000
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /metrics
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-operator-service
  namespace: default
spec:
  selector:
    app: webapp-operator
  ports:
  - port: 8000
    targetPort: 8000
    name: metrics
