apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webapps.platform.devops
spec:
  group: platform.devops
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              replicas:
                type: integer
                minimum: 1
                maximum: 10
              image:
                type: string
              port:
                type: integer
                default: 8080
              resources:
                type: object
                properties:
                  cpu:
                    type: string
                    default: "100m"
                  memory:
                    type: string
                    default: "128Mi"
              affinity:
                type: object
                properties:
                  zone:
                    type: string
                  nodeType:
                    type: string
            required:
            - replicas
            - image
          status:
            type: object
            properties:
              phase:
                type: string
              readyReplicas:
                type: integer
              conditions:
                type: array
                items:
                  type: object
  scope: Namespaced
  names:
    plural: webapps
    singular: webapp
    kind: WebApp
