apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: success-rate
    interval: 30s
    count: 3
    successCondition: result[0] >= 0.95
    failureLimit: 1
    provider:
      prometheus:
        address: http://prometheus-server.monitoring.svc.cluster.local:80
        query: |
          sum(rate(
            http_requests_total{job="{{args.service-name}}",code!~"5.."}[2m]
          )) /
          sum(rate(
            http_requests_total{job="{{args.service-name}}"}[2m]
          ))
