global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'wasm-edge-platform'
    static_configs:
      - targets: ['wasm-edge-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
