version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: infrastructure/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=dev
      - DEBUG=true
    volumes:
      - ../../backend:/app/backend
      - ../../frontend:/app/frontend
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
