global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']
  
  - job_name: 'application'
    static_configs:
      - targets: ['localhost:8000']
