FROM node:18-alpine as builder

WORKDIR /app

COPY dashboard/package*.json ./
RUN npm install

COPY dashboard/ .
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
