apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard-backend
  namespace: k8s-dashboard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-dashboard-backend
  template:
    metadata:
      labels:
        app: k8s-dashboard-backend
    spec:
      serviceAccountName: k8s-dashboard-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: backend
        image: k8s-dashboard-backend:latest
        ports:
        - containerPort: 5000
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
