apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard-frontend
  namespace: k8s-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-dashboard-frontend
  template:
    metadata:
      labels:
        app: k8s-dashboard-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        fsGroup: 101
      containers:
      - name: frontend
        image: k8s-dashboard-frontend:latest
        ports:
        - containerPort: 80
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
