apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard-backend-service
  namespace: k8s-dashboard
spec:
  selector:
    app: k8s-dashboard-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-dashboard-frontend-service
  namespace: k8s-dashboard
spec:
  selector:
    app: k8s-dashboard-frontend
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
