version: '3.8'
services:
  api-service:
    build: 
      context: ./api-service
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./test.db
    volumes:
      - ./api-service:/app
    depends_on:
      - redis

  user-service:
    build:
      context: ./user-service  
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite:///./users.db
    volumes:
      - ./user-service:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_USER_SERVICE_URL=http://localhost:8001
    volumes:
      - ./frontend:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
